In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

c:\Users\15195\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
# Prepare to import the required CSV files
DATA_DIR = Path(r"C:\Users\15195\Desktop\coding part\old dataset")

In [3]:
# Set the CSV file path for each subsequent use
transaction_path = DATA_DIR / "transaction_data.csv"
product_path = DATA_DIR / "product.csv"
hh_demographic_path = DATA_DIR / "hh_demographic.csv"
coupon_path = DATA_DIR / "coupon.csv"
coupon_redempt_path = DATA_DIR / "coupon_redempt.csv"
campaign_table_path = DATA_DIR / "campaign_table.csv"
campaign_desc_path = DATA_DIR / "campaign_desc.csv"

In [4]:
# Check whether each file path exists
paths = {
    "transaction": transaction_path,
    "product": product_path,
    "hh_demographic": hh_demographic_path,
    "coupon": coupon_path,
    "coupon_redempt": coupon_redempt_path,
    "campaign_table": campaign_table_path,
    "campaign_desc": campaign_desc_path
}

for name, path in paths.items():
    print(name, ":", path.exists(), "|", path)

transaction : True | C:\Users\15195\Desktop\coding part\old dataset\transaction_data.csv
product : True | C:\Users\15195\Desktop\coding part\old dataset\product.csv
hh_demographic : True | C:\Users\15195\Desktop\coding part\old dataset\hh_demographic.csv
coupon : True | C:\Users\15195\Desktop\coding part\old dataset\coupon.csv
coupon_redempt : True | C:\Users\15195\Desktop\coding part\old dataset\coupon_redempt.csv
campaign_table : True | C:\Users\15195\Desktop\coding part\old dataset\campaign_table.csv
campaign_desc : True | C:\Users\15195\Desktop\coding part\old dataset\campaign_desc.csv

In [5]:
# Read the most important datasets
transaction = pd.read_csv(transaction_path)
product = pd.read_csv(product_path)
hh_demographic = pd.read_csv(hh_demographic_path)

print("transaction:", transaction.shape)
print("product:", product.shape)
print("hh_demographic:", hh_demographic.shape)

transaction: (2595732, 12)
product: (92353, 7)
hh_demographic: (801, 8)

In [6]:
transaction.head()

,household_key,BASKET_ID,DAY,PRODUCT_ID,QUANTITY,SALES_VALUE,STORE_ID,RETAIL_DISC,TRANS_TIME,WEEK_NO,COUPON_DISC,COUPON_MATCH_DISC
0,2375,26984851472,1,1004906,1,1.39,364,-0.60,1631,1,0.0,0.0
1,2375,26984851472,1,1033142,1,0.82,364,0.00,1631,1,0.0,0.0
2,2375,26984851472,1,1036325,1,0.99,364,-0.30,1631,1,0.0,0.0
3,2375,26984851472,1,1082185,1,1.21,364,0.00,1631,1,0.0,0.0
4,2375,26984851472,1,8160430,1,1.50,364,-0.39,1631,1,0.0,0.0

In [7]:
product.head()

,PRODUCT_ID,MANUFACTURER,DEPARTMENT,BRAND,COMMODITY_DESC,SUB_COMMODITY_DESC,CURR_SIZE_OF_PRODUCT
0,25671,2,GROCERY,National,FRZN ICE,ICE - CRUSHED/CUBED,22 LB
1,26081,2,MISC. TRANS.,National,NO COMMODITY DESCRIPTION,NO SUBCOMMODITY DESCRIPTION,
2,26093,69,PASTRY,Private,BREAD,BREAD:ITALIAN/FRENCH,
3,26190,69,GROCERY,Private,FRUIT - SHELF STABLE,APPLE SAUCE,50 OZ
4,26355,69,GROCERY,Private,COOKIES/CONES,SPECIALTY COOKIES,14 OZ

In [8]:
hh_demographic.head()

,AGE_DESC,MARITAL_STATUS_CODE,INCOME_DESC,HOMEOWNER_DESC,HH_COMP_DESC,HOUSEHOLD_SIZE_DESC,KID_CATEGORY_DESC,household_key
0,65+,A,35-49K,Homeowner,2 Adults No Kids,2,None/Unknown,1
1,45-54,A,50-74K,Homeowner,2 Adults No Kids,2,None/Unknown,7
2,25-34,U,25-34K,Unknown,2 Adults Kids,3,1,8
3,25-34,U,75-99K,Homeowner,2 Adults Kids,4,2,13
4,45-54,B,50-74K,Homeowner,Single Female,1,None/Unknown,16

In [9]:
# Check the columns of the three tables
print(transaction.columns.tolist())
print(product.columns.tolist())
print(hh_demographic.columns.tolist())

['household_key', 'BASKET_ID', 'DAY', 'PRODUCT_ID', 'QUANTITY', 'SALES_VALUE', 'STORE_ID', 'RETAIL_DISC', 'TRANS_TIME', 'WEEK_NO', 'COUPON_DISC', 'COUPON_MATCH_DISC']
['PRODUCT_ID', 'MANUFACTURER', 'DEPARTMENT', 'BRAND', 'COMMODITY_DESC', 'SUB_COMMODITY_DESC', 'CURR_SIZE_OF_PRODUCT']
['AGE_DESC', 'MARITAL_STATUS_CODE', 'INCOME_DESC', 'HOMEOWNER_DESC', 'HH_COMP_DESC', 'HOUSEHOLD_SIZE_DESC', 'KID_CATEGORY_DESC', 'household_key']

In [10]:
# Check the data of the three tables
print("Number of households:", transaction["household_key"].nunique())
print("Number of baskets:", transaction["BASKET_ID"].nunique())
print("Number of products:", transaction["PRODUCT_ID"].nunique())
print("Number of days:", transaction["DAY"].nunique())

Number of households: 2500
Number of baskets: 276484
Number of products: 92339
Number of days: 711

In [11]:
# Check the data of the three tables
pd.set_option("display.float_format", "{:.2f}".format)
transaction[["SALES_VALUE", "QUANTITY"]].describe()

       SALES_VALUE   QUANTITY
count   2595732.00 2595732.00
mean          3.10     100.43
std           4.18    1153.44
min           0.00       0.00
25%           1.29       1.00
50%           2.00       1.00
75%           3.49       1.00
max         840.00   89638.00

In [12]:
# Check for missing values
transaction.isnull().sum()

household_key        0
BASKET_ID            0
DAY                  0
PRODUCT_ID           0
QUANTITY             0
SALES_VALUE          0
STORE_ID             0
RETAIL_DISC          0
TRANS_TIME           0
WEEK_NO              0
COUPON_DISC          0
COUPON_MATCH_DISC    0
dtype: int64

In [13]:
# Check for missing values
product.isnull().sum()

PRODUCT_ID              0
MANUFACTURER            0
DEPARTMENT              0
BRAND                   0
COMMODITY_DESC          0
SUB_COMMODITY_DESC      0
CURR_SIZE_OF_PRODUCT    0
dtype: int64

In [14]:
# Check for missing values
hh_demographic.isnull().sum()

AGE_DESC               0
MARITAL_STATUS_CODE    0
INCOME_DESC            0
HOMEOWNER_DESC         0
HH_COMP_DESC           0
HOUSEHOLD_SIZE_DESC    0
KID_CATEGORY_DESC      0
household_key          0
dtype: int64

In [15]:
# Check exact duplicate rows in the original datasets
print("Exact duplicate rows in transaction:",
      transaction.duplicated().sum())

print("Exact duplicate rows in product:",
      product.duplicated().sum())

print("Exact duplicate rows in hh_demographic:",
      hh_demographic.duplicated().sum())

Exact duplicate rows in transaction: 0
Exact duplicate rows in product: 0
Exact duplicate rows in hh_demographic: 0

In [25]:
# Check transaction-product merge quality
transaction_product_check = transaction.merge(
    product,
    on="PRODUCT_ID",
    how="left",
    indicator=True,
    validate="many_to_one"
)

print(transaction_product_check["_merge"].value_counts())

# Check whether PRODUCT_ID is unique in product table
print("Duplicate PRODUCT_ID in product table:",
      product["PRODUCT_ID"].duplicated().sum())

_merge
both          2595732
left_only           0
right_only          0
Name: count, dtype: int64
Duplicate PRODUCT_ID in product table: 0

In [26]:
# Check transaction-demographic merge quality
transaction_demographic_check = transaction.merge(
    hh_demographic,
    on="household_key",
    how="left",
    indicator=True,
    validate="many_to_one"
)

print(transaction_demographic_check["_merge"].value_counts())

print("Unique households in transaction data:",
      transaction["household_key"].nunique())

print("Households with demographic records:",
      hh_demographic["household_key"].nunique())

_merge
both          1427303
left_only     1168429
right_only          0
Name: count, dtype: int64
Unique households in transaction data: 2500
Households with demographic records: 801

In [27]:
from pathlib import Path

OUTPUT_DIR = Path(
    r"C:\Users\15195\Desktop"
)

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

In [28]:
# Create transaction-product merged dataset
transaction_product = transaction.merge(
    product,
    on="PRODUCT_ID",
    how="left",
    validate="many_to_one"
)

print("transaction_product shape:", transaction_product.shape)
print("Missing product classifications after merge:")

print(
    transaction_product[
        ["DEPARTMENT", "COMMODITY_DESC", "SUB_COMMODITY_DESC"]
    ].isnull().sum()
)

transaction_product shape: (2595732, 18)
Missing product classifications after merge:
DEPARTMENT            0
COMMODITY_DESC        0
SUB_COMMODITY_DESC    0
dtype: int64

In [29]:
# Save transaction-product merged dataset
transaction_product.to_csv(
    OUTPUT_DIR / "transaction_product_merged.csv",
    index=False
)

print("Saved:", OUTPUT_DIR / "transaction_product_merged.csv")

Saved: C:\Users\15195\Desktop\transaction_product_merged.csv

In [30]:
# Create transaction-demographic merged dataset
transaction_demographic = transaction.merge(
    hh_demographic,
    on="household_key",
    how="left",
    validate="many_to_one",
    indicator=True
)

print("transaction_demographic shape:", transaction_demographic.shape)

print("\nMerge result by transaction row:")
print(transaction_demographic["_merge"].value_counts())

transaction_demographic shape: (2595732, 20)

Merge result by transaction row:
_merge
both          1427303
left_only     1168429
right_only          0
Name: count, dtype: int64

In [31]:
#  Check demographic coverage at household level
household_demo_coverage = (
    transaction_demographic[
        ["household_key", "_merge"]
    ]
    .drop_duplicates()
    .groupby("_merge", observed=False)["household_key"]
    .nunique()
)

print("\nMerge result by unique household:")
print(household_demo_coverage)

Merge result by unique household:
_merge
left_only     1699
right_only       0
both           801
Name: household_key, dtype: int64

In [32]:
# Save the full transaction-level merge only if you need it for checking
transaction_demographic.to_csv(
    OUTPUT_DIR / "transaction_demographic_merged.csv",
    index=False
)

print("Saved:", OUTPUT_DIR / "transaction_demographic_merged.csv")

Saved: C:\Users\15195\Desktop\transaction_demographic_merged.csv